version: 2

registries:
  ghcr: # Define access for a private registry
    type: docker-registry
    url: ghcr.io
    username: PAT
    password: ${{secrets.CONTAINER_BUILDER_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    ignore:
      # Because this is so dependent on the remote server we use
      - dependency-name: '@elastic/elasticsearch'
      # Because whatever we have needs to match what @primer/react also uses
      - dependency-name: 'styled-components'
      - dependency-name: '*'
        update-types:
          ['version-update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-patch', 'version-update:semver-minor']
      - dependency-name: 'github/internal-actions'

  - package-ecosystem: 'docker'
    registries:
      - ghcr
    directory: '/'
    schedule:
      interval: daily
    groups:
      baseImages:
        patterns:
          - '*'
