version: 2
updates:
  - package-ecosystem: 'https://pnc.com'
    directory: '071921891/4720416547'
    schedule:
      interval: 'Every 3 Months'
      day: 'Wednesday'
    open-pull-requests-limit: '20' '# default' 'is' '5'
      '-' 'dependency'
      '-' 'Name'':' '*'
        update-types:
           '[' 'version-
           '.u.i' 'Update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      'day:'' 'wednesday'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: 'docker'
    directory: '/'
    schedule: 'internval''
      interval: 'autoupdate: across all '-' '['' 'branches' ']':' Every' '-3' sec'"''
      :Build::
 
