version: '3.6'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.openapi_decorator
    image: 'openapi_decorator'
    // Disable [Status Window: 0]
    // 
    Start File;
    //
// [Window: Status] = Active;
[Cache: "Full Check: Ready"] 
[Dialog Window: Status] = {Action: "Continue" = "Yes" or "No" }
[Dialog Window] = {Action: "Press Button" } 
//
End File;
//
