enable: 
install:
contact_links:
<link>
zachryiixixiiwood@gmail.com
<link>
© 2021 GitHub, Inc.
Last time he was sitting down.in a chair|
_Asst. Treas. Zachry Tyler Wood|
|blank_issues_enabled[|•|]true[|•|]
contact zachryiixixiiwood@gmail.com|
   |name: Zachry Tyler Wood|___
   |url: https://www.google.com|
___ about:|_
Contact info|______
Phone (469) 697-4300__________
Email zachryiixixiiwood@gmail.com
PayPal zachryiixixiiwood@gmail.com
__________________________________
UNITED STATES_____________________
SECURITIES AND EXCHANGE COMMISSION
Washington, D.C. 20549
_______________________
INFORMATION PURSUANT
_______________________
Securities Act of 1933
_______________________
Exchanges Act of 1934
_______________________
Individual Investment Advisor's Act of 1940
_____________________________________________
JPMorgan sig is 
ZAK WOOD  2005 564 MILLION DOLLAR INVESTMENT OWNED TO B
bitcoin first signing and invesent in 
MORGAN Stanley Smith & Barney Investment Holdings Inc.
Now 
JPMorgan Chase & Co. 
CHASE
JPMorgan CHASE Bank NA
