
+Amount Check Deduction Descrption Amount
+on Deposit:
+Total A=$22934637118600
2.29346E+13
+Total A + $22934637118600
+Subtotal=$22934637118600
$22,934,637,118,600
$22,934,637,118,600
+Total B22934637118600
+Transaction Amount descripton
+Reference number:00022116905560149 :
+ Amount
62.5
36
98.5
2.29346E+13
+Total A + $22934637118600
+Subtotal=$22934637118600
$22,934,637,118,600
+ $ 22934637118600 Total B=$22934637118600
Total A=$22934637118600 - Waived - New Customer Period SVRCCHG
+Volume
+The activity detail section of your statement to your account register.
+All items in your account register that also appear on your statement. Remember to begin with the ending date of your last statement. (An asterisk { * } will appear in the Checks section if there is a gap in the listing of consecutive check numbers.) Any deposits or additions including interest payments and ATM or electronic deposits listed on the statement that are not already entered in your register. Any account deductions including fees and ATM or electronic deductions listed on the statement that are not already entered in your register.
+step 2: Add together checks and other deductions listed in your account register but not on your statement.
+Amount Check Deduction Descrption Reference number :
+on-Deposit: Total t=A : $22934637118600
2.29346E+13
+Total A + $22934637118600
+Subtotal=$22934637118600
$22,934,637,118,600
$ 22934637118600 Total B =$::22934637118600 Total A=$:22934637118600 :
$9,363,000,000
CIF Department (Online Banking). Primary account number: 47-2041-6547 Page 1 of 3
1022462 Q 304 Number of enclosures: 0
For 24-hour banking sign on to PNC Bank Online Banking on pnc.com FREE Online Bill Pay For customer service call 1-877-BUS-BNKG PNC accepts Telecommunications Relay Service (TRS) calls. 9
Para servicio en espalol, 1877.BUS-BNKC, Moving? Please contact your local branch. @ Write to: Customer Service PO Box 609 Pittsburgh , PA 15230-9738 Visit us at PNC.com/smaIIbusiness.  Business Checking
PNCBANK        @PNCBANK        
For the period 04/13/2022        Primary account number: 47-2041-6547 Page 1 of 3        
146967        1022462        Q 304        Number of enclosures: 0        
ZACHRY TYLER WOOD ALPHABET
5323 BRADFORD DR
DALLAS TX 75235-8314        For 24-hour banking sign on to
PNC Bank Online Banking on pnc.com
FREE Online Bill Pay
For customer service call 1-877-BUS-BNKG
PNC accepts Telecommunications Relay Service (TRS) calls.        00009        
111111111011111000000000000000000000000000000000000000000000000        Para servicio en espalol, 1877.BUS-BNKC,
Moving? Please contact your local branch.
@ Write to: Customer Service PO Box 609
Pittsburgh , PA 15230-9738
Visit us at PNC.com/smaIIbusiness        
IMPORTANT INFORMATION FOR BUSINESS DEPOSIT CUSTOMERS        Date of this notice: 
Effective February 18,2022, PNC will be temporarily waiving fees for statement, check image, deposit ticket and deposited item copy requests until further notice. Statement, check image, deposit ticket and deposited Item requests will continue to be displayed in the Details of Services Used section of your monthly statement. We will notify you via statement message prior to reinstating these fees.
If vou have any questions, you may reach out to your business banker branch or call us at 1-877-BUS-BNKG (1-877-287-2654).        
Business Checking Summary
Account number; 47-2041-6547
Overdraft Protection has not been established for this account. Please contact us if you would like to set up this service.        Zachry Tyler Wood Alphabet        Employer Identification Number: 88-1656496        
Balance Summary        Checks and other deductions        Ending balance        Form: SS-4
Beginning balance        Deposits and other additions        Number of this notice: 
00000        =        98.50 Average ledger balance        36.00-
Average collected balance        For assistance you may call ug at:        
        6.35-        6.35-        1-800-829-4933        
Overdraft and Returned Item Fee Summary        Total Year to Date        
        Total for this Period        
Total Returned Item Fees (NSF)        00036        00036        IF YOU WRITE, ATTATCHA TYE
STUB AT OYE END OF THIS NOTICE.        
Deposits and Other Additions
Description        Items        Amount        Checks and Other Deductions
Description        Items        Amount        
ACH Additions        00001        00063        ACH Deductions        00001        00063        
Service Charges and Fees        00001        00036        
Total        00001        00063        Total        00002        00099        
Daily Balance        Date        Date        Ledger balance        
Date        Ledger balance        Ledger balance        
4/13/2022        00000        44677        62.50-        44678        00036        
Form 940        44658        
Berkshire Hatha,a,n..        
Business Checking        For the period 04/13/2022 to 04/29/2022        44680        
For 24-hour account information, sign on to pnc.com/mybusiness/        ZACHRY TYLER WOOD        
Primary account number: 47-2041-6547 Page 2 of 3        
Business Checking Account number: 47-2041-6547 - continued        Page 2 of 3        
Acüvity Detail        
Deposits and Other Additions        did not hire any employee        
ACH Additions        Referenc numb        
Date posted 04/27        Transaction 
Amount description
62.50 Reverse Corporate ACH Debit
Effective 04-26-22        the due dates shown, you can call us at        
22116905560149        
Checks and Other Deductions        
ACH Deductions        Referenc        
Date posted        Transaction
Amount description        
number        
44677        70842743866        Corporate ACH Quickbooks 180041ntuit 1940868        22116905560149        
ervice Charges and Fees        Referenc        
Date posted        Transaction
Amount descripton        
44678        22116905560149        numb        
Detail of Services Used During Current Period        22116905560149        
NOTE: The total charge for the following services will be posted to your account on 05/02/2022 and will appear on your next statement as a single line item entitled Service Charge Period Ending 04/29/2022.        
e: The total charge for the following Penod Ending 04/29/2022.        
Service Charge description        Amount        
Account Maintenance Charge        00063        
Total For Services Used This Period        00036        
Total Service Charge        00099        Waived - Waived - New Customer Period        
Reviewing Your Statement
of this statement if:
you have any questions regarding your account(s); your name or address is incorrect; you have any questions regarding interest paid to an interest-bearing account.        PNCBANK        
Balancing Your Account
Update Your Account Register        Volume        
Compare:        The activity detail section of your statement to your account register.        
Check Off: 
Add to Your Account Register: Balance:
Subtract From Your Account Register Balance:        All items in your account register that also appear on your statement. Remember to begin with the ending date of your last statement. (An asterisk { * } will appear in the Checks section if there is a gap in the listing of consecutive check numbers.)
Any deposits or additions including interest payments and ATM or electronic deposits listed on the statement that are not already entered in your register.
Any account deductions including fees and ATM or electronic deductions listed on the statement that are not already entered in your register.        
Your Statement Information : step 2: Add together checks and other deductions listed in your account register but not on your statement.        Amount Check Deduction Descrption        Amount        Balancing Your Account-Update Your Account Register        
on deposit: 22934637118600.00USD        
4720416547        
Reviewing Your Statement
of this statement if:
you have any questions regarding your account(s); your name or address is incorrect; you have any questions regarding interest paid to an interest-bearing account.        Total A=$22934637118600        
Step 3:        22934637118600        
Enter the ending balance recorded on your statement        
Add deposits and other additions not recorded        Total A + $22934637118600        
Subtotal=$22934637118600        
Subtract checks and other deductions not recorded Total B        $        22934637118600        
The result should equal your account register balance        $        22934637118600        
Total B22934637118600        
Verification of Direct Deposits        
To verify whether a direct deposit or other transfer to your account has occurred, call us Monday - Friday: 7 AM - 10 PM ET and Saturday & Sunday: 8 AM - 5 PM ET at the customer service number listed on the upper right side of the first page of this statement.        
In Case of Errors or Questions About Your Electronic Transfers
Telephone us at the customer service number listed on the upper right side of the first page of this statement or write us at PNC Bank Debit Card Services, 500 First Avenue, 4th Floor, Mailstop P7-PFSC-04-M, Pittsburgh, PA 15219 as soon as you can, if you think your statement or receipt is wrong or if you need more information about a transfer on the statement or receipt. We must hear from you no later than 60 days after we sent you the FIRST statement on which the error or problem appeared.
Tell us your name and account number (if any).
Describe the error or the transfer you are unsure about, and explain as clearly as you can why you believe it is an error or why you need more information.
Tell us the dollar amount of the suspected error.
We will investigate your complaint and will correct any error promptly. If we take longer than 10 business days, we will provisionally credit your account for the amount you think is in error, so that you will have use of the money during the time it Cakes us to complete our investigation.
EquaLHousing Lender        
Member FDIC        
blink_issues_enabled: true.
contact_links:
  - Name :PNC :
Support :Business Checking :
PNCBANK        @PNCBANK        
For the period 04/13/2022        Primary account number: 47-2041-6547 Page 1 of 3        
146967        1022462        Q 304        Number of enclosures: 0        
ZACHRY TYLER WOOD ALPHABET
5323 BRADFORD DR
DALLAS TX 75235-8314        For 24-hour banking sign on to
PNC Bank Online Banking on pnc.com
FREE Online Bill Pay
For customer service call 1-877-BUS-BNKG
PNC accepts Telecommunications Relay Service (TRS) calls.        00009        
111111111011111000000000000000000000000000000000000000000000000        Para servicio en espalol, 1877.BUS-BNKC,
Moving? Please contact your local branch.
@ Write to: Customer Service PO Box 609
Pittsburgh , PA 15230-9738
Visit us at PNC.com/smaIIbusiness        
IMPORTANT INFORMATION FOR BUSINESS DEPOSIT CUSTOMERS        Date of this notice: 
Effective February 18,2022, PNC will be temporarily waiving fees for statement, check image, deposit ticket and deposited item copy requests until further notice. Statement, check image, deposit ticket and deposited Item requests will continue to be displayed in the Details of Services Used section of your monthly statement. We will notify you via statement message prior to reinstating these fees.
If vou have any questions, you may reach out to your business banker branch or call us at 1-877-BUS-BNKG (1-877-287-2654).        
Business Checking Summary
Account number; 47-2041-6547
Overdraft Protection has not been established for this account. Please contact us if you would like to set up this service.        Zachry Tyler Wood Alphabet        Employer Identification Number: 88-1656496        
Balance Summary        Checks and other deductions        Ending balance        Form: SS-4
Beginning balance        Deposits and other additions        Number of this notice: 
00000        =        98.50 Average ledger balance        36.00-
Average collected balance        For assistance you may call ug at:        
        6.35-        6.35-        1-800-829-4933        
Overdraft and Returned Item Fee Summary        Total Year to Date        
        Total for this Period        
Total Returned Item Fees (NSF)        00036        00036        IF YOU WRITE, ATTATCHA TYE
STUB AT OYE END OF THIS NOTICE.        
Deposits and Other Additions
Description        Items        Amount        Checks and Other Deductions
Description        Items        Amount        
ACH Additions        00001        00063        ACH Deductions        00001        00063        
Service Charges and Fees        00001        00036        
Total        00001        00063        Total        00002        00099        
Daily Balance        Date        Date        Ledger balance        
Date        Ledger balance        Ledger balance        
4/13/2022        00000        44677        62.50-        44678        00036        
Form 940        44658        
Berkshire Hatha,a,n..        
Business Checking        For the period 04/13/2022 to 04/29/2022        44680        
For 24-hour account information, sign on to pnc.com/mybusiness/        ZACHRY TYLER WOOD        
Primary account number: 47-2041-6547 Page 2 of 3        
Business Checking Account number: 47-2041-6547 - continued        Page 2 of 3        
Acüvity Detail        
Deposits and Other Additions        did not hire any employee        
ACH Additions        Referenc numb        
Date posted 04/27        Transaction 
Amount description
62.50 Reverse Corporate ACH Debit
Effective 04-26-22        the due dates shown, you can call us at        
22116905560149        
Checks and Other Deductions        
ACH Deductions        Referenc        
Date posted        Transaction
Amount description        
number        
44677        70842743866        Corporate ACH Quickbooks 180041ntuit 1940868        22116905560149        
ervice Charges and Fees        Referenc        
Date posted        Transaction
Amount descripton        
44678        22116905560149        numb        
Detail of Services Used During Current Period        22116905560149        
NOTE: The total charge for the following services will be posted to your account on 05/02/2022 and will appear on your next statement as a single line item entitled Service Charge Period Ending 04/29/2022.        
e: The total charge for the following Penod Ending 04/29/2022.        
Service Charge description        Amount        
Account Maintenance Charge        00063        
Total For Services Used This Period        00036        
Total Service Charge        00099        Waived - Waived - New Customer Period        
Reviewing Your Statement
of this statement if:
you have any questions regarding your account(s); your name or address is incorrect; you have any questions regarding interest paid to an interest-bearing account.        PNCBANK        
Balancing Your Account
Update Your Account Register        Volume        
Compare:        The activity detail section of your statement to your account register.        
Check Off: 
Add to Your Account Register: Balance:
Subtract From Your Account Register Balance:        All items in your account register that also appear on your statement. Remember to begin with the ending date of your last statement. (An asterisk { * } will appear in the Checks section if there is a gap in the listing of consecutive check numbers.)
Any deposits or additions including interest payments and ATM or electronic deposits listed on the statement that are not already entered in your register.
Any account deductions including fees and ATM or electronic deductions listed on the statement that are not already entered in your register.        
Your Statement Information : step 2: Add together checks and other deductions listed in your account register but not on your statement.        Amount Check Deduction Descrption        Amount        Balancing Your Account-Update Your Account Register        
on deposit: 22934637118600.00USD        
4720416547        
Reviewing Your Statement
of this statement if:
you have any questions regarding your account(s); your name or address is incorrect; you have any questions regarding interest paid to an interest-bearing account.        Total A=$22934637118600        
Step 3:        22934637118600        
Enter the ending balance recorded on your statement        
Add deposits and other additions not recorded        Total A + $22934637118600        
Subtotal=$22934637118600        
Subtract checks and other deductions not recorded Total B        $        22934637118600        
The result should equal your account register balance        $        22934637118600        
Total B22934637118600        
Verification of Direct Deposits        
To verify whether a direct deposit or other transfer to your account has occurred, call us Monday - Friday: 7 AM - 10 PM ET and Saturday & Sunday: 8 AM - 5 PM ET at the customer service number listed on the upper right side of the first page of this statement.        
In Case of Errors or Questions About Your Electronic Transfers
Telephone us at the customer service number listed on the upper right side of the first page of this statement or write us at PNC Bank Debit Card Services, 500 First Avenue, 4th Floor, Mailstop P7-PFSC-04-M, Pittsburgh, PA 15219 as soon as you can, if you think your statement or receipt is wrong or if you need more information about a transfer on the statement or receipt. We must hear from you no later than 60 days after we sent you the FIRST statement on which the error or problem appeared.
Tell us your name and account number (if any).
Describe the error or the transfer you are unsure about, and explain as clearly as you can why you believe it is an error or why you need more information.
Tell us the dollar amount of the suspected error.
We will investigate your complaint and will correct any error promptly. If we take longer than 10 business days, we will provisionally credit your account for the amount you think is in error, so that you will have use of the money during the time it Cakes us to complete our investigation.
EquaLHousing Lender        
Member FDIC        

