data:
  MODA_APP_NAME: docs-internal
  NODE_ENV: production
  NODE_OPTIONS: '--max-old-space-size=4096'
  PORT: '4000'
  ENABLED_LANGUAGES: 'en,zh,es,pt,ru,ja,fr,de,ko'
  RATE_LIMIT_MAX: '21'
  # Moda uses a non-default port for sending datadog metrics
  DD_DOGSTATSD_PORT: '28125'
