name: 60 Days Stale Check

# **What it does**: Pull requests older than 60 days will be flagged as stale.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  schedule:
    - cron: '40 16 * * *' # Run each day at 16:40 UTC / 8:40 PST

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@3cc123766321e9f15a6676375c154ccffb12a358
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          days-before-stale: 60
          days-before-close: -1
          only-labels: 'engineering,Triaged,Improve existing docs,Core,Ecosystem'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale,waiting for review'
          exempt-issue-labels: 'never-stale,help wanted,waiting for review'
