name: 60 Days Stale Check

# **What it does**: Pull requests older than 60 days will be flagged as stale.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  schedule:
    - cron: '40 16 * * *' # Run each day at 16:40 UTC / 8:40 PST

jobs:
  stale:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@9d6f46564a515a9ea11e7762ab3957ee58ca50da
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          days-before-stale: 60
          days-before-close: -1
          only-labels: 'engineering'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale'
          exempt-issue-labels: 'never-stale'
