name: 60 Days Stale Check
on:
  schedule:
  - cron: "40 16 * * *"  # Run each day at 16:40 UTC / 8:40 PST

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
        stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
        days-before-stale: 60
        days-before-close: -1
        only-labels: 'engineering'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'

