name: Build Docker image

# **What it does**: This builds our Docker container.
# **Why we have it**: We don't use the Docker container internally, but other teams depend on our Docker container.
# **Who does it impact**: Enterprise customers.

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  build:
    # Do not run this job for translations PRs
    if: ${{ github.head_ref != 'translations' && github.ref != 'refs/heads/translations' }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - name: Build the container
        run: docker build --target production .
