name: Content Changes Table Comment

# **What it does**: When a PR is opened in docs-internal or docs, it adds the staging preview and live article links in a Content Directory Changes table in a comment
# **Why we have it**: To help Docs Content team members and contributors automatically have their staging/live article links added to the table
# **Who does it impact**: docs-internal/docs maintainers and contributors

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  PR-Preview-Links:
    if: github.event.pull_request.user.login != 'docs-bot' && (github.repository == 'github/docs-internal' || github.repository == 'github/docs')
    name: Add staging/live links to PR
    runs-on: ubuntu-latest
    outputs:
      filterContentDir: ${{ steps.filter.outputs.filterContentDir }}
    steps:
      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Get files changed
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          # Base branch used to get changed files
          base: ${{ github.event.pull_request.base.ref }}

          # Enables setting an output in the format in `${FILTER_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            filterContentDir:
              - 'content/**/*'

      - uses: ./.github/actions/slack-alert
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}

  filterContentDir:
    needs: PR-Preview-Links
    if: ${{ needs.PR-Preview-Links.outputs.filterContentDir == 'true' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: check out repo content
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Get preview app info
        env:
          APP_NAME_SEED: ${{ secrets.PREVIEW_ENV_NAME_SEED }}
        run: src/workflows/get-preview-app-info.sh

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install temporary dependencies
        run: |
          npm install --no-save github-slugger --registry https://registry.npmjs.org/

      - name: Get changes table
        id: changes
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_URL: ${{ env.APP_URL }}
        run: src/workflows/content-changes-table-comment.js

      - name: Find content directory changes comment
        uses: peter-evans/find-comment@f4499a714d59013c74a08789b48abe4b704364a0
        id: findComment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- MODIFIED_CONTENT_LINKING_COMMENT -->'

      - name: Update comment
        if: ${{ steps.changes.outputs.changesTable != '' }}
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- MODIFIED_CONTENT_LINKING_COMMENT -->
            ## Automatically generated comment ℹ️
            **This comment is automatically generated and will be overwritten every time changes are committed to this branch.**

            The table contains an overview of files in the `content` directory that have been changed in this pull request. It's provided to make it easy to review your changes on the staging site. Please note that changes to the `data` directory will not show up in this table.

            ---

            ### Content directory changes
            _You may find it useful to copy this table into the pull request summary. There you can edit it to share links to important articles or changes and to give a high-level overview of how the changes in your pull request support the overall goals of the pull request._
            ${{ steps.changes.outputs.changesTable }}

            ---
            fpt: Free, Pro, Team
            ghec: GitHub Enterprise Cloud
            ghes: GitHub Enterprise Server
            ghae: GitHub AE
          edit-mode: replace

      - uses: ./.github/actions/slack-alert
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
