name: Automatic comment to request feedback on PR experience

# What it does: When PRs are merged, generate an automatic comment asking for feedback.
# Why we have it: So Hubbers can leave us feedback on the DIY Docs experience.
# Who it impacts: All Hubbers

on:
  pull_request:
    types:
      - closed

jobs:
  add-comment:
    if: github.repository == 'github/docs-internal' && github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Please leave feedback on the contributor experience! Leave a ğŸ‘ or ğŸ‘. You can also reach us in `#docs-contributor-feedback` on Slack."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
