name: (Dry run) Search indexes

# **What it does**: On request, dry run to check for issues with search indexing.
# **Why we have it**: It helps us debug issues with search indexing.
# **Who does it impact**: Docs engineering.

on:
  workflow_dispatch:

jobs:
  updateIndices:
    name: (Dry run) Update indices
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Node
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run build scripts
        run: npm run build
      - name: (Dry run) sync indices
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run sync-search-dry-run
