name: Keep caches warm

# **What it does**: Makes sure the caching of ./node_modules and ./.next
#                   is kept warm for making pull requests more rapid.
# **Why we have it**: A PR workflow that depends on caching can't reuse a
#                     cached artifact acorss PRs unless it also runs on `main`.
# **Who does it impact**: Docs engineering, open-source engineering contributors.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  keep-caches-warm:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ${{ fromJSON('["ubuntu-latest", "ubuntu-20.04-xl"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - uses: ./.github/actions/node-npm-setup

      - uses: ./.github/actions/cache-nextjs

      - name: Build
        run: npm run build

      - uses: ./.github/actions/warmup-remotejson-cache

      - uses: ./.github/actions/slack-alert
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
