on:
  pull_request_target:
    types: ['closed']

jobs:
  comment:
    if: github.event.repository.private == false && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          script: |
            github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: 'Thanks very much for contributing! Your pull request has been merged ðŸŽ‰ You should see your changes appear on the site in approximately 24 hours.'
            })
