name: Merged notification

# **What it does**: When we merge an open-source pull request, we want to set expectations that deployment may take awhile.
# **Why we have it**: We deploy to production from docs-internal, not docs.
# **Who does it impact**: Open-source contributors.

on:
  pull_request_target:
    types:
      - 'closed'

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    if: github.repository == 'github/docs' && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'Octomerger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c
        with:
          script: |
            github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: "Thanks very much for contributing! Your pull request has been merged ðŸŽ‰ You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:"
            })
