name: Move and unlabel ready to merge PRs

# **What it does**: When a PR in the open source repo is labeled "ready to merge," the "waiting for review" label is removed and the PR is moved to the "Triage" column.
# **Why we have it**: To help with managing our project boards.
# **Who does it impact**: Open source contributors, open-source maintainers.

on:
  pull_request_target:
    types:
      - labeled

permissions:
  pull-requests: write

jobs:
  unmark_for_review:
    if: >-
      ${{
        github.repository == 'github/docs' &&
        github.event.label.name == 'ready to merge'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: move PR
        uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Docs open source board
          column: Triage
          repo-token: ${{ secrets.DOCS_BOT_PAT_WORKFLOW_READORG }}

      - name: remove label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          ignore-if-assigned: 'false'
          remove-labels: 'waiting for review'
