name: Move help wanted issues

# **What it does**: In the open source repo, when the "help wanted" or "good first issue" labels are added to an issue, the issue is added to the "Help wanted" column on the project board.
# **Why we have it**: To keep track of help wanted issues.
# **Who does it impact**: Open-source contributors.

on:
  issues:
    types:
      - labeled

permissions:
  contents: none

jobs:
  move_issues:
    if: >-
      ${{
        github.repository == 'github/docs' &&
        (github.event.label.name == 'help wanted' || github.event.label.name == 'good first issue')
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488
        with:
          project: Docs open source board
          column: Help wanted
          repo-token: ${{ secrets.DOCUBOT_READORG_REPO_WORKFLOW_SCOPES }}
