name: Move and unlabel ready to merge PRs

# **What it does**: When a PR in the open source repo is labeled "ready to merge," the "waiting for review" label is removed and the PR is moved to the "Triage" column.
# **Why we have it**: To help with managing our project boards.
# **Who does it impact**: Open source contributors, open-source maintainers.

on:
  # Needed in lieu of `pull_request` so that the a PR from a fork can trigger the project board and label automation.
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  unmark_for_review:
    if: >-
      ${{
        github.repository == 'github/docs' &&
        github.event.label.name == 'ready to merge'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: move PR
        uses: alex-page/github-project-automation-plus@303f24a24c67ce7adf565a07e96720faf126fe36
        with:
          project: Docs open source board
          column: Triage
          repo-token: ${{ secrets.DOCS_BOT_PAT_BASE }}

      - name: Check out repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/actions/node-npm-setup

      - name: remove label
        uses: ./.github/actions/labeler
        with:
          ignoreifAssigned: 'false'
          removeLabels: 'waiting for review'
