name: Notify about production deployment

# **What it does**: Posts a comment on the PR whose merge got into production.
# **Why we have it**: So that the PR author can be informed when their merged PR is in production.
# **Who does it impact**: Writers

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Purge Fastly']
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  find-pr-and-post-comment:
    if: >-
      ${{
        github.repository == 'github/docs-internal' &&
        (github.event_name != 'workflow_run' ||
        github.event.workflow_run.conclusion == 'success')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/node-npm-setup

      # The "Purge Fastly" action takes about 6 minutes to purge all
      # languages. First does the language agnostic URLs, then English,
      # then all the other languages.
      # So it takes about ~30 seconds until it has sent the purge for
      # all English docs.
      - name: Sleep a little to give Fastly Purge a chance
        run: sleep 30

      - name: Find last PR
        id: get-number
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        run: npm run find-past-built-pr

      - name: Find content directory changes comment
        if: ${{ steps.get-number.outputs.number != '' }}
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: findComment
        with:
          issue-number: ${{ steps.get-number.outputs.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- GONE_TO_PRODUCTION -->'

      - name: Update comment
        if: ${{ steps.get-number.outputs.number != '' }}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ steps.get-number.outputs.number }}
          body: |
            <!-- GONE_TO_PRODUCTION -->
            ðŸš€ **This pull request has gone into production!**

            The SHA of https://docs.github.com/_build matches the merge commit in this PR.

            If you don't see updates when expected, try adding a random query string to the URL like `?bla=1234` and see if that helps.
            If that shows the expected content, it would indicate that the CDN is "overly caching" the page still. It will eventually update, but it can take a while.
          edit-mode: replace

      - uses: ./.github/actions/slack-alert
        if: ${{ failure() }}
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
