name: Open Enterprise release or deprecation issue

# **What it does**: Checks if there is an Enterprise release or deprecation upcoming, and if so, opens an issue with the tasks to be completed.
# **Why we have it**: GHES releases and deprecations run on a predictable schedule, so we can automate some of the project management aspects.
# **Who does it impact**: Docs engineering, docs content.

on:
  workflow_dispatch:
  schedule:
    - cron: '49 14 * * *' # At 14:49 UTC daily

permissions:
  contents: read

jobs:
  open_enterprise_issue:
    name: Open Enterprise issue
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Setup Node
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048
        with:
          node-version: '16.15.0'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check for existing release or deprecation issues
        id: existingIssue
        run: |
          .github/actions-scripts/check-for-enterprise-issues-by-label.js
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}

      - name: Update enterprise dates
        if: steps.existingIssue.outputs.deprecationIssue == 'false' || steps.existingIssue.outputs.releaseIssue == 'false'
        run: |
          script/update-enterprise-dates.js
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}

      - name: Create an enterprise release issue
        if: steps.existingIssue.outputs.releaseIssue == 'false'
        run: |
          .github/actions-scripts/create-enterprise-issue.js release
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}

      - name: Create an enterprise deprecation issue
        if: steps.existingIssue.outputs.deprecationIssue == 'false'
        run: |
          .github/actions-scripts/create-enterprise-issue.js deprecation
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}
