name: 'Orphaned assets check'

# **What it does**: Checks that there are no files in ./assets/ that aren't mentioned in any source file.
# **Why we have it**: To avoid orphans into the repo.
# **Who does it impact**: Docs content.

on:
  pull_request:

permissions:
  contents: read

jobs:
  orphaned-assets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16.14.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Check for orphaned assets
        run: ./script/find-orphaned-assets.mjs --verbose --exit
