name: OS Ready for review

# **What it does**: Adds pull requests and issues in the docs repository to the docs-content review board when the "waiting for review" label is added
# **Why we have it**: So that contributors in the OS repo can easily get reviews from the docs-content team, and so that writers can see when a PR is ready for review
# **Who does it impact**: Writers working in the docs repository
on:
  pull_request_target:
    types: [labeled]
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  request_doc_review:
    name: Request a review from the docs-content team
    if: github.event.label.name == 'waiting for review' && github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - name: Check if this run was triggered by a member of the docs team
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: triggered-by-member
        with:
          github-token: ${{secrets.DOCUBOT_READORG_REPO_WORKFLOW_SCOPES}}
          result-encoding: string
          script: |
            const triggerer_login = context.payload.sender.login
            const teamMembers = await github.request(
              `/orgs/github/teams/docs/members?per_page=100`
            )
            const logins = teamMembers.data.map(member => member.login)
            if (logins.includes(triggerer_login)) {
              console.log(`This workflow was triggered by ${triggerer_login} (on the docs team).`)
              return 'true'
            }
            console.log(`This workflow was triggered by ${triggerer_login} (not on the docs team), so no action will be taken.`)
            return 'false'

      - name: Exit if not triggered by a docs team member
        if: steps.triggered-by-member.outputs.result == 'false'
        run: |
          echo Aborting. This workflow must be triggered by a member of the docs team.
          exit 1

      - name: Check out repo content
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run script
        run: |
          node .github/actions-scripts/ready-for-docs-review.js
        env:
          TOKEN: ${{ secrets.DOCS_BOT_FR }}
          PROJECT_NUMBER: 2936
          ORGANIZATION: 'github'
          ITEM_NODE_ID: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
          AUTHOR_LOGIN: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
          REPO: ${{ github.repository }}
