name: Ping staging apps

# **What it does**: This keeps our staging applications from automatically spinning down.
# **Why we have it**: Staging applications can hiberate without use.
# **Who does it impact**: Anyone with a pull request in docs-internal.

on:
  schedule:
    - cron: '10,30,50 * * * *' # every twenty minutes

jobs:
  ping_staging_apps:
    name: Ping
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - name: Setup node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.8.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: Run script
        run: script/ping-staging-apps.js
