name: Remove stale staging resources

# **What it does**:
# This cleans up any rogue staging applications and environments that outlasted
# the closure of their corresponding pull requests.
# **Why we have it**:
# Staging applications and environments sometimes fail to be destroyed when
# their corresponding pull request is closed or merged.
# **Who does it impact**:
# Anyone with a closed, spammy, or deleted pull request in docs or docs-internal.

on:
  schedule:
    - cron: '15,45 * * * *' # every thirty minutes at :15 and :45

permissions:
  contents: read
  pull-requests: read

jobs:
  remove_stale_staging_apps:
    name: Remove stale staging apps
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: script/remove-stale-staging-apps.js
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove_stale_staging_envs:
    name: Remove stale staging environments
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: script/remove-stale-staging-envs.js
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}
          REPO: ${{ github.repository }}
