name: Reviewers - Content Systems

# **What it does**: Automatically add reviewers based on paths, but only for the docs-internal repo.
# **Why we have it**: So we can have reviewers automatically without getting open source notifications.
# **Who does it impact**: Docs team.

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - 'contributing/content-*.md'
      - 'content/contributing/**.md'
      - .github/workflows/reviewers-content-systems.yml

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  reviewers-content-systems:
    if: >-
      ${{ github.repository == 'github/docs-internal' &&
          !github.event.pull_request.draft &&
          !contains(github.event.pull_request.labels.*.name, 'reviewers-content-systems') &&
          github.event.pull_request.head.ref != 'repo-sync' }}
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0

      - name: Add content systems as a reviewer
        uses: ./.github/actions/retry-command
        with:
          command: gh pr edit $PR --add-reviewer github/docs-content-systems --add-label reviewers-content-systems
