name: Reviewers - Dependabot

# **What it does**: Automatically add reviewers based on paths, for docs-internal and docs repos.
# **Why we have it**: So dependabot maintainers can be notified about relevant pull requests.
# **Who does it impact**: dependabot-updates-reviewers.

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - 'data/reusable/dependabot/**'
      - 'content/code-security/dependabot/**'
      - 'content/rest/dependabot/**'
      - '.github/workflows/reviewers-dependabot.yml'

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  reviewers-dependabot:
    if: >-
      ${{ github.repository == 'github/docs-internal' &&
          !github.event.pull_request.draft &&
          !contains(github.event.pull_request.labels.*.name, 'reviewers-dependabot') &&
          github.event.pull_request.head.ref != 'repo-sync' }}
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Add dependabot as a reviewer
        uses: ./.github/actions/retry-command
        with:
          command: gh pr edit $PR --add-reviewer github/dependabot-updates-reviewers --add-label reviewers-dependabot
