name: Staging - Undeploy PR

# **What it does**: To undeploy PRs from a Heroku staging environment, i.e. destroy the Heroku App.
# **Why we have it**: To save money spent on deployments for closed PRs.
# **Who does it impact**: All contributors.

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  deployments: write
  pull-requests: write

# This prevents one Undeploy workflow run from interrupting another
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}'
  cancel-in-progress: false

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump full context for debugging
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  cancel-jobs-before-undeploy:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    # This interrupts Build and Deploy workflow runs in progress for this PR
    # branch. However, it does so with an intentionally short, independent job
    # so that the following `undeploy` job cannot be cancelled once started!
    concurrency:
      group: 'PR Staging @ ${{ github.event.pull_request.head.label }}'
      cancel-in-progress: true
    steps:
      - name: Cancelling other deployments via concurrency configuration
        run: |
          echo 'Cancelling other deployment runs (if any)...'

  undeploy:
    needs: cancel-jobs-before-undeploy
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # IMPORTANT: Intentionally OMIT a `concurrency` configuration from this job!
    steps:
      - name: Add a label to the PR to block deployment during undeployment
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'automated-block-deploy'

      - name: Check out repo's default branch
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          # For enhanced security: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
          persist-credentials: 'false'

      - name: Setup node
        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Undeploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: .github/actions-scripts/staging-undeploy.js

      - if: ${{ always() }}
        name: Remove the label from the PR to unblock deployment
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          remove-labels: 'automated-block-deploy'

      - name: Send Slack notification if workflow failed
        uses: someimportantcompany/github-actions-slack-message@dafca0835f7e51f42ec46806aced9230fa56b058
        if: ${{ failure() }}
        with:
          channel: ${{ secrets.DOCS_STAGING_DEPLOYMENT_FAILURES_SLACK_CHANNEL_ID }}
          bot-token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
          color: failure
          text: Staging undeployment failed for PR ${{ github.event.pull_request.html_url }} at commit ${{ github.head_sha }}. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
