name: Start new engineering PR workflow

on: 
  pull_request: 
    types: [opened, reopened]
    
jobs:
  triage:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DRAFT_COLUMN_ID: 10095775
      REGULAR_COLUMN_ID: 10095779
    steps:
    - name: 
      uses: actions/github-script@v2
      with:
          github-token: ${{ secrets.DOCUBOT_FR_PROJECT_BOARD_WORKFLOWS_REPO_ORG_READ_SCOPES }}
          script: |
              // Only assign the engineering folks
              try { 
                await github.teams.getMembershipForUserInOrg({
                  org: 'github',
                  team_slug: 'docs-engineering',
                  username: context.payload.sender.login,
                });
              } catch(err) {
                return
              }

              // Set column ID
              const column_id = context.payload.pull_request.draft
                ? process.env.DRAFT_COLUMN_ID
                : process.env.REGULAR_COLUMN_ID

              // Try to create the card on the GitHub Project
              try {
                await github.projects.createCard({
                  column_id: column_id,
                  content_type: 'PullRequest',
                  content_id: context.payload.pull_request.id
                });
              } catch(error) {
                console.log(error);
              }


              // Try to set the author as the assignee
              const owner = context.payload.repository.owner.login
              const repo = context.payload.repository.name

              try {
                await github.issues.addAssignees({
                  owner: owner,
                  repo: repo,
                  issue_number: context.payload.pull_request.number,
                  assignees: [
                    context.payload.sender.login
                  ]
                });
              } catch(error) {
                console.log(error);
              }
