name: Triage new pull requests

# **What it does**: Adds triage label to new pull requests in the open source repository.
# **Why we have it**: Update project board for new pull requests for triage.
# **Who does it impact**: Docs open source.

on:
  # Needed in lieu of `pull_request` so that PRs from a fork can be triaged.
  pull_request_target:
    types:
      - reopened
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_pulls:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/node-npm-setup

      - name: Label new pull requests with 'triage'
        uses: ./.github/actions/labeler
        with:
          addLabels: 'triage'
