name: Triage new issues

# **What it does**: Add the 'triage' label to new issues in the open source repository.
# **Why we have it**: We want to make sure that new issues are triaged and assigned to the right team.
# **Who does it impact**: Docs open source.

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  contents: read
  issues: write

jobs:
  triage_issues:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/node-npm-setup

      - name: Label new issues with 'triage'
        uses: ./.github/actions/labeler
        with:
          addLabels: 'triage'
