name: Triage new pull requests

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  pull_request_target:
    types:
      - reopened
      - opened

jobs:
  triage_pulls:
    if: github.repository != 'github/docs-internal'
    runs-on: ubuntu-latest

    steps:
      - name: Label new pull requests with 'triage'
        uses: rachmari/labeler@540b235a26368529afa318e56fea423b16039a06
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          add-labels: 'triage'
      - name: Triage to project board
        uses: rachmari/actions-add-new-issue-to-column@1a459ef92308ba7c9c9dc2fcdd72f232495574a9
        with:
          action-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: 'https://github.com/github/docs/projects/1'
          column-name: 'Triage'
