name: Public Repo Stale Check

# **What it does**: Provides more aggressive stale checks in the open repo.
# **Why we have it**: In the open repo, we want more aggressive stale checking.
# **Who does it impact**: Anyone working in the open repo.

on:
  schedule:
    - cron: '45 16 * * *' # Run each day at 16:45 UTC / 8:45 PST

permissions:
  issues: write
  pull-requests: write

jobs:
  stale_contributor:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@7fb802b3079a276cf3c7e6ba9aa003c665b3f838
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'A stale label has been added to this issue becuase it has been open for 60 days with no activity. To keep this issue open, add a comment within 3 days.'
          days-before-issue-stale: 60
          days-before-issue-close: 3
          exempt-issue-labels: 'help wanted,waiting for review'
          stale-pr-message: 'A stale label has been added to this pull request because it has been open 7 days with no activity. To keep this PR open, add a comment or push a commit within 3 days.'
          days-before-pr-stale: 7
          days-before-pr-close: 3
          stale-pr-label: 'stale'
          exempt-pr-labels: 'waiting for review,never-stale,ready to merge'
  stale_staff:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@7fb802b3079a276cf3c7e6ba9aa003c665b3f838
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This is a gentle bump for the docs team that this PR is waiting for review.'
          days-before-pr-stale: 14
          days-before-pr-close: -1 # Never close
          remove-stale-when-updated: false
          operations-per-run: 100
          only-labels: 'waiting for review'
          # The hope is that by setting the stale-pr-label to the same label
          # as the label that the stale check looks for, this will result in
          # a comment being posted every 14 days as an infinite loop, which is what
          # we want
          stale-pr-label: 'waiting for review'
          exempt-pr-labels: 'never-stale'
