name: Triage new issue comments

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  triage-issue-comments:
    if: ${{ github.repository == 'github/docs' && !github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Check if the event originated from a team member
        uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da
        id: is-internal-contributor
        with:
          result-encoding: string
          script: |
            const repo = context.payload.repository.name
            const org = context.payload.repository.owner.login
            const actor = context.actor
            let collaboratorStatus = ''
            try {
              collaboratorStatus = await github.request('GET /repos/{owner}/{repo}/collaborators/{username}', {
                owner: org,
                repo: repo,
                username: actor
              })
              console.log(`This issue was commented on by a Hubber.`)
              return 'true'
            } catch (error) {
              console.log(`This issue was commented on by an external contributor.`)
              return 'false'
            }
      - name: Label issues with new comments with 'triage'
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        if: ${{ steps.is-internal-contributor.outputs.result == 'false' }}
        with:
          add-labels: 'triage'
          ignore-if-labeled: true
