name: Public Repo Stale Check
on:
  schedule:
    - cron: '45 16 * * *' # Run each day at 16:45 UTC / 8:45 PST

jobs:
  stale:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@af4072615903a8b031f986d25b1ae3bf45ec44d4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open 21 days with no activity and will be automatically closed in 10 days. To keep this PR open, update the PR by adding a comment or pushing a commit.'
          days-before-stale: 21
          days-before-close: 10
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale'
          exempt-issue-labels: 'never-stale'
