name: Validate asset images

# **What it does**: Run ./src/assets/scripts/validate-asset-images.ts on all images in assets/
# **Why we have it**: To protect from innocent and potentially malicious bad image assets
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**'
      - '.github/workflows/validate-asset-images.yml'

permissions:
  contents: read

jobs:
  validate-asset-images:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/node-npm-setup

      - name: Validate all asset images
        run: npm run validate-asset-images
